// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: models/models.proto

package pdfcompose

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File1 []byte `protobuf:"bytes,1,opt,name=File1,proto3" json:"File1,omitempty"`
	File2 []byte `protobuf:"bytes,2,opt,name=File2,proto3" json:"File2,omitempty"`
	File3 []byte `protobuf:"bytes,3,opt,name=File3,proto3" json:"File3,omitempty"`
}

func (x *SendParams) Reset() {
	*x = SendParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendParams) ProtoMessage() {}

func (x *SendParams) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendParams.ProtoReflect.Descriptor instead.
func (*SendParams) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *SendParams) GetFile1() []byte {
	if x != nil {
		return x.File1
	}
	return nil
}

func (x *SendParams) GetFile2() []byte {
	if x != nil {
		return x.File2
	}
	return nil
}

func (x *SendParams) GetFile3() []byte {
	if x != nil {
		return x.File3
	}
	return nil
}

type Responce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *Responce) Reset() {
	*x = Responce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Responce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responce) ProtoMessage() {}

func (x *Responce) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responce.ProtoReflect.Descriptor instead.
func (*Responce) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *Responce) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_models_models_proto protoreflect.FileDescriptor

var file_models_models_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x65, 0x22, 0x4e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x46, 0x69, 0x6c, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x69, 0x6c, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65,
	0x33, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x32, 0x4b, 0x0a, 0x11, 0x50, 0x64, 0x66, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x16,
	0x2e, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x42, 0x1d,
	0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6c, 0x6e,
	0x6e, 0x6b, 0x2f, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_models_proto_rawDescOnce sync.Once
	file_models_models_proto_rawDescData = file_models_models_proto_rawDesc
)

func file_models_models_proto_rawDescGZIP() []byte {
	file_models_models_proto_rawDescOnce.Do(func() {
		file_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_models_proto_rawDescData)
	})
	return file_models_models_proto_rawDescData
}

var file_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_models_proto_goTypes = []interface{}{
	(*SendParams)(nil), // 0: pdfcompose.SendParams
	(*Responce)(nil),   // 1: pdfcompose.Responce
}
var file_models_models_proto_depIdxs = []int32{
	0, // 0: pdfcompose.PdfComposeService.Send:input_type -> pdfcompose.SendParams
	1, // 1: pdfcompose.PdfComposeService.Send:output_type -> pdfcompose.Responce
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_models_proto_init() }
func file_models_models_proto_init() {
	if File_models_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Responce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_models_proto_goTypes,
		DependencyIndexes: file_models_models_proto_depIdxs,
		MessageInfos:      file_models_models_proto_msgTypes,
	}.Build()
	File_models_models_proto = out.File
	file_models_models_proto_rawDesc = nil
	file_models_models_proto_goTypes = nil
	file_models_models_proto_depIdxs = nil
}
